version: '3.7'
services:

  hello:
    container_name: testapi
    build:
      context: ./hello-world/
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  operations-view:
    container_name: opsview
    build:
      context: ./operationview
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
